server:
  port: 9000

spring:
  application:
    name: aimp-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true # Enable auto discovery of services
          lower-case-service-id: true
      routes:
        - id: aimp-user-service
          uri: lb://aimp-user-service
          predicates:
            - Path=/api/**

# Sa-Token Configuration
sa-token: 
  token-name: Authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: simple-uuid
  is-log: true
  jwt:
    # Must match the secret in aimp-user
    secret-key: aimp-microservice-secret-key-for-jwt-token-authentication
