spring:
  application:
    name: openaimp-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/openaimp?serverTimeZone=UTC
    username: root
    password: ${DB_PASSWORD:ab321818}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mail:
    host: smtp.qq.com
    port: 587
    username: amstudio@qq.com
    password: ${MAIL_PASSWORD:ojxeivkzyineddaj}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3000ms
      database: 0

server:
  port: 6067

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.type: DEBUG

sa-token:
  token-name: aerion
  timeout: 2592000
  active-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true

url:
  whazzup: https://data.vatsim.net/v3/vatsim-data.json

openfsd:
  api:
    base-url: http://localhost:8000
  admin:
    cid: 1
    password: ab321818


